# Generated by Django 2.2.13 on 2020-12-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0005_auto_20201211_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
