# Generated by Django 2.2.13 on 2020-12-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20190831_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
    ]
