# Generated by Django 2.2.13 on 2020-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
