# Generated by Django 2.2.13 on 2020-12-11 21:47

from django.db import migrations, models
import inv.models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20201204_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Categoría', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Marca', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=inv.models.Producto.autonumber_productCode, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default=inv.models.Producto.autonumber_SKUCode, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Categoría', max_length=50),
        ),
    ]
