# Generated by Django 2.2.13 on 2020-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
