# Generated by Django 2.2 on 2020-11-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_subcategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name_plural': 'Sub Categorias'},
        ),
    ]
