# Generated by Django 2.2.13 on 2020-12-04 21:48

from django.db import migrations, models
import inv.models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20201129_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Categoría', max_length=50, unique=True, validators=[inv.models.validarnombre]),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Marca', max_length=50, unique=True, validators=[inv.models.validarnombre]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[inv.models.validarnumero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(max_length=50, validators=[inv.models.validarnumero]),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Categoría', max_length=50, validators=[inv.models.validarnombre]),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Unidad Medida', max_length=50, unique=True),
        ),
    ]
